language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
dist: xenial
sudo: required
env:
  global:
#    - OPAM_VERSION=2.0
matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    env: OCAML_VERSION=4.09
  - os: freebsd
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.09 INSTALL_LOCAL=1
  - os: linux
    env: OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
  allow_failures:
  - os: freebsd
    env: OCAML_VERSION=4.09
notifications:
  email:
  - opam-commits@lists.ocaml.org
  irc:
  - chat.freenode.net#opam
